services:
  - type: web
    name: LaravelApp
    runtime: php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: your-laravel-key
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-app-name.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: RENDER_PHP_VERSION
        value: 8.1
    buildCommand: |
      apt-get update && apt-get install -y unzip
      curl -sS https://getcomposer.org/installer | php
      mv composer.phar /usr/local/bin/composer
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
